version: '3'
tasks:
  build:
    env:
      CGO_ENABLED: 0
    cmds:
      - go build -ldflags="-s -w" -trimpath -o ./out/fda{{exeExt}} .

  run:
    deps:
      - build
    cmds:
      - ./out/fda{{exeExt}} -host=127.0.0.1 -port=18080